### ISSUE TITLE
ToolContainer helpers should be public

### ISSUE THREAD

**Issue by lzell** [FunctionCalling/FunctionCalling-AIProxySwift#11]
I believe the following should be public:

- `func toOpenAITools(strict: Bool = false) -> [AIProxyOpenAITool]`
- `func toAnthropicTools() -> [AIProxyAnthropicTool]`
-  `func toTogetherAITools() -> [AIProxyTogetherAITool]`

See this screenshot when trying to add the README's sample code to a project:

![Screenshot 2024-12-23 at 19 53 22](https://github.com/user-attachments/assets/f7c733d0-b65d-4d00-a7f8-4f930a26219f)

**Comment by fumito-ito** [comment]
@lzell Thanks for your reporting. I fixed it.
